-- b0-003-catalogo-de-permissoes
--
-- Seed de sistema (Documento 7 §22): o catálogo de permissões é do código —
-- `packages/contracts/src/identidade/permissoes.ts` — e esta migration só o
-- espelha no banco. `packages/contracts/test/catalogo.test.mjs` (T29c)
-- exige que os dois conjuntos de códigos sejam iguais, nos dois sentidos.
-- Sem `pessoas.anamnese.responder_por_terceiro` (Doc 6 §2.6: sem caso de
-- uso). Os grupos por instituição e as permissões deles NÃO entram aqui —
-- são da I04.

INSERT INTO identidade.permissao (codigo, modulo, descricao) VALUES
  ('financeiro.lancamento.registrar',        'financeiro', 'Registrar lançamento'),
  ('financeiro.lancamento.confirmar',        'financeiro', 'Confirmar lançamento na verificação'),
  ('financeiro.lancamento.estornar',         'financeiro', 'Estornar lançamento confirmado'),
  ('financeiro.lancamento.ler',              'financeiro', 'Ler todos os lançamentos'),
  ('financeiro.lancamento.ler_proprios',     'financeiro', 'Ler os próprios registros'),
  ('financeiro.transferencia.registrar',     'financeiro', 'Registrar transferência'),
  ('financeiro.conta.ler',                   'financeiro', 'Ler contas e saldos'),
  ('financeiro.conta.gerenciar',             'financeiro', 'Criar e editar contas'),
  ('financeiro.fundo.gerenciar',             'financeiro', 'Gerenciar fundos'),
  ('financeiro.fatura.gerenciar',            'financeiro', 'Gerenciar faturas de cartão'),
  ('financeiro.emprestimo.gerenciar',        'financeiro', 'Gerenciar empréstimos'),
  ('financeiro.adiantamento.registrar',      'financeiro', 'Registrar adiantamento'),
  ('financeiro.adiantamento.autorizar',      'financeiro', 'Autorizar adiantamento (exige vínculo — A1)'),
  ('financeiro.adiantamento.ressarcir',      'financeiro', 'Ressarcir adiantamento'),
  ('financeiro.reembolsos.ler',              'financeiro', 'Ler reembolsos pendentes'),
  ('financeiro.importacao.executar',         'financeiro', 'Importar extrato'),
  ('financeiro.conciliacao.executar',        'financeiro', 'Conciliar extrato'),
  ('financeiro.periodo.fechar',              'financeiro', 'Fechar competência'),
  ('financeiro.periodo.reabrir',             'financeiro', 'Reabrir competência'),
  ('financeiro.plano_contas.ler',            'financeiro', 'Ler plano de contas'),
  ('financeiro.plano_contas.gerenciar',      'financeiro', 'Gerenciar plano de contas'),
  ('financeiro.dre.ler',                     'financeiro', 'Ler DRE'),
  ('financeiro.fluxo_caixa.ler',             'financeiro', 'Ler fluxo de caixa'),
  ('financeiro.resultado_evento.ler',        'financeiro', 'Ler resultado por cerimônia'),
  ('financeiro.prestacao_contas.gerar',      'financeiro', 'Gerar prestação de contas'),
  ('financeiro.prestacao_contas.detalhada',  'financeiro', 'Gerar prestação detalhada (com identidades)'),
  ('eventos.evento.criar',                   'eventos',    'Criar evento'),
  ('eventos.evento.editar',                  'eventos',    'Editar evento'),
  ('eventos.evento.cancelar',                'eventos',    'Cancelar evento'),
  ('eventos.evento.realizar',                'eventos',    'Marcar evento como realizado'),
  ('eventos.inscricoes.abrir',               'eventos',    'Abrir e encerrar inscrições'),
  ('eventos.inscricao.ler',                  'eventos',    'Ler inscrições'),
  ('eventos.inscricao.registrar',            'eventos',    'Registrar inscrição'),
  ('eventos.inscricao.editar',               'eventos',    'Editar inscrição'),
  ('eventos.inscricao.confirmar',            'eventos',    'Confirmar inscrição'),
  ('eventos.inscricao.cancelar',             'eventos',    'Cancelar inscrição'),
  ('eventos.pagamento.registrar',            'eventos',    'Marcar pagamento de contribuição'),
  ('eventos.arrecadacao.ler',                'eventos',    'Ler arrecadação do evento'),
  ('eventos.devolucao.solicitar',            'eventos',    'Registrar pedido de devolução'),
  ('eventos.devolucao.efetivar',             'eventos',    'Pagar devolução'),
  ('eventos.contratacao.gerenciar',          'eventos',    'Gerenciar contratação'),
  ('eventos.acolhimento.registrar',          'eventos',    'Registrar acolhimento'),
  ('eventos.operacao.ler',                   'eventos',    'Ler operação (leitos, refeições)'),
  ('eventos.operacao.gerenciar',             'eventos',    'Gerenciar operação (leitos, refeições)'),
  ('pessoas.pessoa.ler',                     'pessoas',    'Ler pessoas'),
  ('pessoas.pessoa.registrar',               'pessoas',    'Cadastrar pessoa'),
  ('pessoas.pessoa.editar',                  'pessoas',    'Editar pessoa'),
  ('pessoas.pessoa.anonimizar',              'pessoas',    'Anonimizar pessoa (LGPD)'),
  ('pessoas.vinculo.gerenciar',              'pessoas',    'Gerenciar papéis e vínculos'),
  ('pessoas.anamnese.ler',                   'pessoas',    'Ler respostas de anamnese'),
  ('pessoas.anamnese.analisar',              'pessoas',    'Dar parecer sobre anamnese'),
  ('pessoas.formulario.editar',              'pessoas',    'Editar formulário de anamnese'),
  ('pessoas.formulario.publicar',            'pessoas',    'Publicar versão do formulário'),
  ('pessoas.consentimento.registrar',        'pessoas',    'Registrar consentimento'),
  ('pessoas.autorizacao_responsavel.registrar','pessoas',  'Registrar autorização de responsável'),
  ('estoque.saldo.ler',                      'estoque',    'Ler saldo'),
  ('estoque.item.gerenciar',                 'estoque',    'Gerenciar itens'),
  ('estoque.movimento.registrar',            'estoque',    'Registrar movimento'),
  ('estoque.consumo.registrar',              'estoque',    'Registrar consumo de cerimônia'),
  ('estoque.feitio.gerenciar',               'estoque',    'Gerenciar feitio'),
  ('sistema.usuario.gerenciar',              'sistema',    'Gerenciar usuários'),
  ('sistema.grupo.gerenciar',                'sistema',    'Gerenciar grupos'),
  ('sistema.parametro.gerenciar',            'sistema',    'Gerenciar parâmetros'),
  ('sistema.auditoria.ler',                  'sistema',    'Ler trilha de auditoria');
