/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface IdentidadeConvite {
  criado_em: Generated<Timestamp>;
  criado_por: string;
  expira_em: Timestamp;
  id: Generated<string>;
  instituicao_id: string;
  revogado_em: Timestamp | null;
  token_sha256: Buffer;
  usado_em: Timestamp | null;
  usuario_id: string;
}

export interface IdentidadeGrupo {
  ativo: Generated<boolean>;
  codigo_sistema: string | null;
  descricao: Generated<string>;
  id: Generated<string>;
  instituicao_id: string;
  nome: string;
  protegido: Generated<boolean>;
  versao: Generated<number>;
}

export interface IdentidadeGrupoPermissao {
  grupo_id: string;
  instituicao_id: string;
  permissao: string;
}

export interface IdentidadePermissao {
  codigo: string;
  descricao: string;
  modulo: string;
}

export interface IdentidadeRegistroDeAuditoria {
  agregado_id: string;
  agregado_tipo: string;
  autor_grupos: string[];
  autor_tipo: Generated<string>;
  autor_usuario_id: string | null;
  correlacao_id: string | null;
  detalhes: Generated<Json>;
  em: Generated<Timestamp>;
  id: Generated<string>;
  instituicao_id: string;
  operacao: string;
  pessoa_alvo_id: string | null;
  sensivel: Generated<boolean>;
}

export interface IdentidadeUsuario {
  ativado_em: Timestamp | null;
  criado_em: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  instituicao_id: string;
  nome: string;
  pessoa_id: string | null;
  situacao: string;
  subject_id: string | null;
  suspenso_em: Timestamp | null;
  ultimo_acesso_em: Timestamp | null;
  versao: Generated<number>;
}

export interface IdentidadeUsuarioGrupo {
  atribuido_em: Generated<Timestamp>;
  atribuido_por: string;
  grupo_id: string;
  instituicao_id: string;
  usuario_id: string;
}

export interface SharedChaveDeIdempotencia {
  chave: string;
  criada_em: Generated<Timestamp>;
  instituicao_id: string;
  resposta: Json;
  rota: string;
  status_http: number;
  usuario_id: string | null;
}

export interface SharedEventoProcessado {
  consumidor: string;
  evento_id: string;
  processado_em: Generated<Timestamp>;
}

export interface SharedInstituicao {
  criada_em: Generated<Timestamp>;
  id: Generated<string>;
  nome: string;
}

export interface SharedOutbox {
  agregado_id: string;
  agregado_tipo: string;
  evento_id: string;
  id: Generated<number>;
  instituicao_id: string;
  ocorrido_em: Generated<Timestamp>;
  payload: Json;
  proxima_tentativa_em: Timestamp | null;
  publicado_em: Timestamp | null;
  tentativas: Generated<number>;
  tipo: string;
  ultimo_erro: string | null;
}

export interface DB {
  "identidade.convite": IdentidadeConvite;
  "identidade.grupo": IdentidadeGrupo;
  "identidade.grupo_permissao": IdentidadeGrupoPermissao;
  "identidade.permissao": IdentidadePermissao;
  "identidade.registro_de_auditoria": IdentidadeRegistroDeAuditoria;
  "identidade.usuario": IdentidadeUsuario;
  "identidade.usuario_grupo": IdentidadeUsuarioGrupo;
  "shared.chave_de_idempotencia": SharedChaveDeIdempotencia;
  "shared.evento_processado": SharedEventoProcessado;
  "shared.instituicao": SharedInstituicao;
  "shared.outbox": SharedOutbox;
}
