export const CODIGOS_DE_ERRO = [
  'NAO_AUTENTICADO',
  'SEM_PERMISSAO',
  'RECURSO_NAO_ENCONTRADO',
  'CORPO_INVALIDO',
  'VERSAO_DESATUALIZADA',
  'VERSAO_OBRIGATORIA',
  'CHAVE_DE_IDEMPOTENCIA_REUTILIZADA',
  'CONFLITO_DE_CONCORRENCIA',
  'SERVICO_INDISPONIVEL',
  'ERRO_INTERNO',
  'CORPO_GRANDE_DEMAIS',
  'GRUPO_JA_EXISTE',
  'CONVITE_JA_PENDENTE',

  'CATEGORIA_OBRIGATORIA',
  'ETIQUETAS_NAO_FECHAM',
  'FEITIO_IMUTAVEL',
  'LANCAMENTO_IMUTAVEL',
  'PERIODO_FECHADO',
  'REGISTRO_IMUTAVEL',
  'SALDO_INSUFICIENTE',
  'TRANSFERENCIA_IMUTAVEL',

  'USUARIO_DESCONHECIDO',
  'USUARIO_CONVITE_PENDENTE',
  'USUARIO_SUSPENSO',
  'USUARIO_REVOGADO',
  'SITUACAO_DO_USUARIO_NAO_PERMITE',
  'ULTIMO_ADMINISTRADOR',
  'EMAIL_JA_CADASTRADO',
  'PESSOA_JA_TEM_USUARIO',
  'CONVITE_INVALIDO',
  'CONVITE_EXPIRADO',
  'CONVITE_JA_USADO',
  'GRUPO_INEXISTENTE',
  'PERMISSAO_INEXISTENTE',
  'GRUPO_PROTEGIDO',
  'GRUPO_COM_USUARIOS_ATIVOS',
  'MOTIVO_OBRIGATORIO',
  'MOTIVO_LONGO_DEMAIS',
  'PROVEDOR_DE_IDENTIDADE_INDISPONIVEL',
] as const;

export type CodigoDeErro = (typeof CODIGOS_DE_ERRO)[number];

export interface CorpoDeErro {
  readonly erro: CodigoDeErro;
  readonly detalhes?: Record<string, unknown>;
  readonly correlacaoId: string;
}
