export * from './kernel.js';
export * from './erros.js';
export * from './financeiro.js';
export * from './eventos.js';
export * from './pessoas.js';
export * from './identidade/index.js';
export * from './estoque.js';
export * from './readmodels.js';
export * from './comandos/identidade.js';
