export const CATALOGO_DE_PERMISSOES = {
  'financeiro.lancamento.registrar': { modulo: 'financeiro', descricao: 'Registrar lançamento' },
  'financeiro.lancamento.confirmar': { modulo: 'financeiro', descricao: 'Confirmar lançamento na verificação' },
  'financeiro.lancamento.estornar': { modulo: 'financeiro', descricao: 'Estornar lançamento confirmado' },
  'financeiro.lancamento.ler': { modulo: 'financeiro', descricao: 'Ler todos os lançamentos' },
  'financeiro.lancamento.ler_proprios': { modulo: 'financeiro', descricao: 'Ler os próprios registros' },
  'financeiro.transferencia.registrar': { modulo: 'financeiro', descricao: 'Registrar transferência' },
  'financeiro.conta.ler': { modulo: 'financeiro', descricao: 'Ler contas e saldos' },
  'financeiro.conta.gerenciar': { modulo: 'financeiro', descricao: 'Criar e editar contas' },
  'financeiro.fundo.gerenciar': { modulo: 'financeiro', descricao: 'Gerenciar fundos' },
  'financeiro.fatura.gerenciar': { modulo: 'financeiro', descricao: 'Gerenciar faturas de cartão' },
  'financeiro.emprestimo.gerenciar': { modulo: 'financeiro', descricao: 'Gerenciar empréstimos' },
  'financeiro.adiantamento.registrar': { modulo: 'financeiro', descricao: 'Registrar adiantamento' },
  'financeiro.adiantamento.autorizar': { modulo: 'financeiro', descricao: 'Autorizar adiantamento (exige vínculo — A1)' },
  'financeiro.adiantamento.ressarcir': { modulo: 'financeiro', descricao: 'Ressarcir adiantamento' },
  'financeiro.reembolsos.ler': { modulo: 'financeiro', descricao: 'Ler reembolsos pendentes' },
  'financeiro.importacao.executar': { modulo: 'financeiro', descricao: 'Importar extrato' },
  'financeiro.conciliacao.executar': { modulo: 'financeiro', descricao: 'Conciliar extrato' },
  'financeiro.periodo.fechar': { modulo: 'financeiro', descricao: 'Fechar competência' },
  'financeiro.periodo.reabrir': { modulo: 'financeiro', descricao: 'Reabrir competência' },
  'financeiro.plano_contas.ler': { modulo: 'financeiro', descricao: 'Ler plano de contas' },
  'financeiro.plano_contas.gerenciar': { modulo: 'financeiro', descricao: 'Gerenciar plano de contas' },
  'financeiro.dre.ler': { modulo: 'financeiro', descricao: 'Ler DRE' },
  'financeiro.fluxo_caixa.ler': { modulo: 'financeiro', descricao: 'Ler fluxo de caixa' },
  'financeiro.resultado_evento.ler': { modulo: 'financeiro', descricao: 'Ler resultado por cerimônia' },
  'financeiro.prestacao_contas.gerar': { modulo: 'financeiro', descricao: 'Gerar prestação de contas' },
  'financeiro.prestacao_contas.detalhada': {
    modulo: 'financeiro',
    descricao: 'Gerar prestação detalhada (com identidades)',
  },
  'eventos.evento.criar': { modulo: 'eventos', descricao: 'Criar evento' },
  'eventos.evento.editar': { modulo: 'eventos', descricao: 'Editar evento' },
  'eventos.evento.cancelar': { modulo: 'eventos', descricao: 'Cancelar evento' },
  'eventos.evento.realizar': { modulo: 'eventos', descricao: 'Marcar evento como realizado' },
  'eventos.inscricoes.abrir': { modulo: 'eventos', descricao: 'Abrir e encerrar inscrições' },
  'eventos.inscricao.ler': { modulo: 'eventos', descricao: 'Ler inscrições' },
  'eventos.inscricao.registrar': { modulo: 'eventos', descricao: 'Registrar inscrição' },
  'eventos.inscricao.editar': { modulo: 'eventos', descricao: 'Editar inscrição' },
  'eventos.inscricao.confirmar': { modulo: 'eventos', descricao: 'Confirmar inscrição' },
  'eventos.inscricao.cancelar': { modulo: 'eventos', descricao: 'Cancelar inscrição' },
  'eventos.pagamento.registrar': { modulo: 'eventos', descricao: 'Marcar pagamento de contribuição' },
  'eventos.arrecadacao.ler': { modulo: 'eventos', descricao: 'Ler arrecadação do evento' },
  'eventos.devolucao.solicitar': { modulo: 'eventos', descricao: 'Registrar pedido de devolução' },
  'eventos.devolucao.efetivar': { modulo: 'eventos', descricao: 'Pagar devolução' },
  'eventos.contratacao.gerenciar': { modulo: 'eventos', descricao: 'Gerenciar contratação' },
  'eventos.acolhimento.registrar': { modulo: 'eventos', descricao: 'Registrar acolhimento' },
  'eventos.operacao.ler': { modulo: 'eventos', descricao: 'Ler operação (leitos, refeições)' },
  'eventos.operacao.gerenciar': { modulo: 'eventos', descricao: 'Gerenciar operação (leitos, refeições)' },
  'pessoas.pessoa.ler': { modulo: 'pessoas', descricao: 'Ler pessoas' },
  'pessoas.pessoa.registrar': { modulo: 'pessoas', descricao: 'Cadastrar pessoa' },
  'pessoas.pessoa.editar': { modulo: 'pessoas', descricao: 'Editar pessoa' },
  'pessoas.pessoa.anonimizar': { modulo: 'pessoas', descricao: 'Anonimizar pessoa (LGPD)' },
  'pessoas.vinculo.gerenciar': { modulo: 'pessoas', descricao: 'Gerenciar papéis e vínculos' },
  'pessoas.anamnese.ler': { modulo: 'pessoas', descricao: 'Ler respostas de anamnese' },
  'pessoas.anamnese.analisar': { modulo: 'pessoas', descricao: 'Dar parecer sobre anamnese' },
  'pessoas.formulario.editar': { modulo: 'pessoas', descricao: 'Editar formulário de anamnese' },
  'pessoas.formulario.publicar': { modulo: 'pessoas', descricao: 'Publicar versão do formulário' },
  'pessoas.consentimento.registrar': { modulo: 'pessoas', descricao: 'Registrar consentimento' },
  'pessoas.autorizacao_responsavel.registrar': {
    modulo: 'pessoas',
    descricao: 'Registrar autorização de responsável',
  },
  'estoque.saldo.ler': { modulo: 'estoque', descricao: 'Ler saldo' },
  'estoque.item.gerenciar': { modulo: 'estoque', descricao: 'Gerenciar itens' },
  'estoque.movimento.registrar': { modulo: 'estoque', descricao: 'Registrar movimento' },
  'estoque.consumo.registrar': { modulo: 'estoque', descricao: 'Registrar consumo de cerimônia' },
  'estoque.feitio.gerenciar': { modulo: 'estoque', descricao: 'Gerenciar feitio' },
  'sistema.usuario.gerenciar': { modulo: 'sistema', descricao: 'Gerenciar usuários' },
  'sistema.grupo.gerenciar': { modulo: 'sistema', descricao: 'Gerenciar grupos' },
  'sistema.parametro.gerenciar': { modulo: 'sistema', descricao: 'Gerenciar parâmetros' },
  'sistema.auditoria.ler': { modulo: 'sistema', descricao: 'Ler trilha de auditoria' },
} as const;

export type Permissao = keyof typeof CATALOGO_DE_PERMISSOES;

export const PERMISSOES = Object.keys(CATALOGO_DE_PERMISSOES) as readonly Permissao[];
